M48
; DRILL file {KiCad 9.0.7} date 2026-01-24T01:09:57+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-24T01:09:57+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X189.11Y-99.25
X194.89Y-99.25
T2
X174.0Y-76.0
M30
